# Generated by Django 3.2 on 2021-07-13 13:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('accountName', models.CharField(blank=True, max_length=200)),
                ('accountNumber', models.CharField(blank=True, max_length=200)),
                ('salary', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('stock_100', models.PositiveIntegerField(default=0)),
                ('stock_500', models.PositiveIntegerField(default=0)),
                ('stock_1000', models.PositiveIntegerField(default=0)),
                ('price_100', models.PositiveIntegerField(default=0)),
                ('price_500', models.PositiveIntegerField(default=0)),
                ('price_1000', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_image', models.ImageField(upload_to='photos')),
                ('prod_id', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to='listingsapi.products')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default='Cash', max_length=50)),
                ('delivery_status', models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Delivered', max_length=50)),
                ('total', models.IntegerField()),
                ('added_date', models.DateField(auto_now_add=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listingsapi.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_size', models.IntegerField(default=100)),
                ('quantity', models.IntegerField()),
                ('ord_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listingsapi.orders')),
                ('prod_id', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to='listingsapi.products')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_category', models.CharField(choices=[('Operation', 'Operations'), ('Management', 'Management'), ('Investment', 'Investment')], default='Operation', max_length=50)),
                ('amount', models.IntegerField()),
                ('description', models.TextField()),
                ('added_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
