# Generated by Django 3.2 on 2021-07-13 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listingsapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_category', models.CharField(choices=[('Operation', 'Operations'), ('Management', 'Management'), ('Investment', 'Investment')], default='Operation', max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('added_date', models.DateField(auto_now_add=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Expenses',
        ),
    ]
