# Generated by Django 3.2 on 2021-07-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingsapi', '0002_auto_20210713_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_expense',
            name='expense_category',
            field=models.CharField(choices=[('Operation', 'Operations'), ('Management', 'Management'), ('Miscellaneous', 'Miscellaneous')], default='Operation', max_length=50),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='salary',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='prod_size',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total',
            field=models.PositiveIntegerField(),
        ),
    ]
