# Generated by Django 3.2 on 2021-07-16 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listingsapi', '0003_auto_20210716_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listingsapi.customers'),
        ),
    ]
