# Generated by Django 3.2 on 2021-07-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingsapi', '0004_alter_orders_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
